# Generated by Django 3.2.6 on 2022-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_cattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Disclaimer',
            field=models.TextField(default='no'),
        ),
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(default='Square', max_length=100),
        ),
    ]
