# Generated by Django 3.2.6 on 2022-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_image', models.ImageField(upload_to='presimg')),
            ],
        ),
    ]
