# Generated by Django 3.2.6 on 2022-02-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadprescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadprescription',
            name='myuser',
        ),
    ]
