# Generated by Django 3.2.6 on 2022-02-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_uploadprescription_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprescription',
            name='newuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
