# Generated by Django 3.2.6 on 2022-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_uploadprescription_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('specialist', models.CharField(max_length=200)),
                ('chamber', models.CharField(max_length=300)),
                ('chamber_address', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=50)),
                ('visiting_hour', models.CharField(max_length=200)),
                ('new_patient_fee', models.IntegerField()),
                ('old_patient_fee', models.IntegerField()),
                ('report_checking_fee', models.IntegerField()),
                ('doctor_img', models.ImageField(upload_to='doctorimg')),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Dhaka Metro', 'Dhaka Metro'), ('Dhaka Mirpur 10', 'Dhaka Mirpur 10'), ('Dhaka Gulshan', 'Dhaka Gulshan'), ('Dhaka Mirpur 12', 'Dhaka Mirpur 12'), ('Sylhet', 'Sylhet'), ('Kanaigat', 'Kanaigat'), ('Beanibazar', 'Beanibazar'), ('Golapgonj', 'Golapgonj'), ('Jkoigonj', 'Joigonj')], default='Dhaka', max_length=50)),
            ],
        ),
    ]
