# Generated by Django 3.2.6 on 2022-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_doctorinfo_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='doctor_img',
            field=models.ImageField(blank=True, null=True, upload_to='doctorimg'),
        ),
    ]
