# Generated by Django 3.2.6 on 2022-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_doctorinfo_doctor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='new_patient_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='old_patient_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='report_checking_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
